# Generated by Django 5.2.17 on 2026-09-20 08:46

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lookups", "0001_initial"),
        ("pipelines", "0001_initial"),
    ]

    operations = [
        CreateExtension("vector"),
        migrations.CreateModel(
            name="Week",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "week_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_on", models.DateField(unique=True)),
                ("ends_on", models.DateField()),
                ("season", models.IntegerField()),
                ("label", models.CharField(blank=True, default="", max_length=80)),
            ],
            options={
                "ordering": ["-starts_on"],
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("handle", models.CharField(max_length=80)),
                ("first_seen_at", models.DateTimeField()),
                ("voice_count", models.IntegerField(default=0)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authors",
                        to="lookups.lksources",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("summary", models.TextField(blank=True, default="")),
                ("centroid", pgvector.django.vector.VectorField(dimensions=384)),
                ("size", models.IntegerField(default=0)),
                ("rank", models.IntegerField(default=0)),
                (
                    "cluster_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topics",
                        to="pipelines.pipelinerun",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="voices.week",
                    ),
                ),
            ],
            options={
                "ordering": ["week", "rank"],
            },
        ),
        migrations.CreateModel(
            name="Voice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "voice_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=32)),
                ("external_url", models.URLField(max_length=500)),
                ("depth", models.IntegerField(blank=True, null=True)),
                ("title", models.TextField(blank=True, default="")),
                ("body_text", models.TextField(blank=True, default="")),
                ("body_html", models.TextField(blank=True, default="")),
                ("flair", models.CharField(blank=True, default="", max_length=80)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("reply_count", models.IntegerField(blank=True, null=True)),
                ("posted_at", models.DateTimeField()),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voices",
                        to="voices.author",
                    ),
                ),
                (
                    "ingest_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingested_voices",
                        to="pipelines.pipelinerun",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="voices.voice",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voices",
                        to="lookups.lksources",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="voices.voice",
                    ),
                ),
                (
                    "voice_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voices",
                        to="lookups.lkvoicetypes",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voices",
                        to="voices.week",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reading_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("intensity", models.FloatField()),
                ("sarcasm", models.BooleanField(default=False)),
                ("gist", models.TextField(blank=True, default="")),
                (
                    "subjects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=80),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("model", models.CharField(max_length=80)),
                ("prompt_version", models.CharField(max_length=32)),
                ("raw", models.JSONField(default=dict)),
                (
                    "mood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="lookups.lkmoods",
                    ),
                ),
                (
                    "tag_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="pipelines.pipelinerun",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="lookups.lktargets",
                    ),
                ),
                (
                    "voice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="voices.voice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Embedding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "embedding_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vector", pgvector.django.vector.VectorField(dimensions=384)),
                ("model", models.CharField(max_length=80)),
                ("source_text", models.TextField()),
                ("x", models.FloatField(blank=True, null=True)),
                ("y", models.FloatField(blank=True, null=True)),
                ("retrieval_count", models.IntegerField(default=0)),
                (
                    "embed_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="embeddings",
                        to="pipelines.pipelinerun",
                    ),
                ),
                (
                    "projection_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projections",
                        to="pipelines.pipelinerun",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="embeddings",
                        to="voices.topic",
                    ),
                ),
                (
                    "voice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="voices.voice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("espn_event_id", models.CharField(max_length=32, unique=True)),
                ("opponent", models.CharField(max_length=80)),
                ("opponent_abbreviation", models.CharField(max_length=8)),
                ("kickoff_at", models.DateTimeField()),
                ("is_home", models.BooleanField()),
                ("venue", models.CharField(blank=True, default="", max_length=120)),
                ("status", models.CharField(default="scheduled", max_length=32)),
                ("steelers_score", models.IntegerField(blank=True, null=True)),
                ("opponent_score", models.IntegerField(blank=True, null=True)),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="voices.week",
                    ),
                ),
            ],
            options={
                "ordering": ["kickoff_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(fields=("source", "handle"), name="uniq_author_per_source"),
        ),
        migrations.AddConstraint(
            model_name="reading",
            constraint=models.UniqueConstraint(fields=("voice", "tag_run"), name="uniq_reading_per_run"),
        ),
        migrations.AddConstraint(
            model_name="reading",
            constraint=models.CheckConstraint(
                condition=models.Q(("intensity__gte", 0), ("intensity__lte", 1)),
                name="intensity_is_unit",
            ),
        ),
        migrations.AddIndex(
            model_name="embedding",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["vector"],
                m=16,
                name="embedding_vector_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="voice",
            index=models.Index(fields=["week", "posted_at"], name="voices_voic_week_id_23ffae_idx"),
        ),
        migrations.AddIndex(
            model_name="voice",
            index=models.Index(fields=["thread", "posted_at"], name="voices_voic_thread__151e79_idx"),
        ),
        migrations.AddConstraint(
            model_name="voice",
            constraint=models.UniqueConstraint(fields=("source", "external_id"), name="uniq_voice_per_source"),
        ),
    ]
