# Generated by Django 5.2.17 on 2026-09-20 08:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lookups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pipeline_run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        choices=[
                            ("local", "local"),
                            ("rig", "rig"),
                            ("remote", "remote"),
                        ],
                        default="local",
                        max_length=16,
                    ),
                ),
                ("dry_run", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("log_excerpt", models.TextField(blank=True, default="")),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="lookups.lkpipelines",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
