# Generated by Django 5.2.17 on 2026-09-20 08:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LKArms",
            fields=[
                ("label", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "arm_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
                ("uses_retrieval", models.BooleanField()),
            ],
            options={
                "ordering": ["sort_order", "label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LKExperimentKinds",
            fields=[
                ("label", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "experiment_kind_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
            ],
            options={
                "ordering": ["sort_order", "label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LKMetrics",
            fields=[
                ("label", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "metric_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
                ("unit", models.CharField(blank=True, default="", max_length=32)),
                ("higher_is_better", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LKMoods",
            fields=[
                ("label", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "mood_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "color_token",
                    models.CharField(blank=True, default="", max_length=40),
                ),
            ],
            options={
                "ordering": ["sort_order", "label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LKPipelines",
            fields=[
                ("label", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pipeline_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("local_schedule", models.CharField(max_length=64)),
                ("remote_schedule", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["sort_order", "label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LKSectionKinds",
            fields=[
                ("label", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "section_kind_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
            ],
            options={
                "ordering": ["sort_order", "label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LKSources",
            fields=[
                ("label", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("platform", models.CharField(max_length=40)),
                ("community", models.CharField(max_length=80)),
                ("url", models.URLField()),
                ("posts_feed_url", models.URLField()),
                ("comments_feed_url", models.URLField()),
                (
                    "adapter",
                    models.CharField(choices=[("archive", "archive"), ("rss", "rss")], max_length=16),
                ),
            ],
            options={
                "ordering": ["sort_order", "label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LKTargets",
            fields=[
                ("label", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "target_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
            ],
            options={
                "ordering": ["sort_order", "label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LKVoiceTypes",
            fields=[
                ("label", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "voice_type_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
            ],
            options={
                "ordering": ["sort_order", "label"],
                "abstract": False,
            },
        ),
    ]
