# Generated by Django 5.2.17 on 2026-09-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lookups", "0002_drop_source_adapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="lksectionkinds",
            name="question",
            field=models.TextField(blank=True, default=""),
        ),
    ]
